/*
 * generated by Xtext
 */
package org.xtext.example.domainmodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DomainmodelRuntimeModule extends org.xtext.example.domainmodel.AbstractDomainmodelRuntimeModule {

}
