/*
* generated by Xtext
*/
package org.xtext.example.domainmodel.ui.contentassist;

import org.xtext.example.domainmodel.ui.contentassist.AbstractDomainmodelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DomainmodelProposalProvider extends AbstractDomainmodelProposalProvider {

}
